# fly.toml app configuration file generated for tournament-bracket-ws on 2026-02-04T03:56:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tournament-bracket-ws'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.alive]
    port = 8080
    type = 'http'
    path = '/health'
    interval = '15s'
    timeout = '2s'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
